export function countryFlag(code) {
  if (!code || code.length !== 2) return "";
  const cp = code.toUpperCase().split("").map(c => 0x1F1E6 + c.charCodeAt(0) - 65);
  return String.fromCodePoint(...cp);
}

export const allCountries = [
  { label: "Afghanistan", code: "AF", currency: "AFN" },
  { label: "Albania", code: "AL", currency: "ALL" },
  { label: "Algeria", code: "DZ", currency: "DZD" },
  { label: "Andorra", code: "AD", currency: "EUR" },
  { label: "Angola", code: "AO", currency: "AOA" },
  { label: "Argentina", code: "AR", currency: "ARS" },
  { label: "Armenia", code: "AM", currency: "AMD" },
  { label: "Australia", code: "AU", currency: "AUD" },
  { label: "Austria", code: "AT", currency: "EUR" },
  { label: "Azerbaijan", code: "AZ", currency: "AZN" },
  { label: "Bahamas", code: "BS", currency: "BSD" },
  { label: "Bahrain", code: "BH", currency: "BHD" },
  { label: "Bangladesh", code: "BD", currency: "BDT" },
  { label: "Barbados", code: "BB", currency: "BBD" },
  { label: "Belarus", code: "BY", currency: "BYN" },
  { label: "Belgium", code: "BE", currency: "EUR" },
  { label: "Belize", code: "BZ", currency: "BZD" },
  { label: "Benin", code: "BJ", currency: "XOF" },
  { label: "Bhutan", code: "BT", currency: "BTN" },
  { label: "Bolivia", code: "BO", currency: "BOB" },
  { label: "Bosnia & Herzegovina", code: "BA", currency: "BAM" },
  { label: "Botswana", code: "BW", currency: "BWP" },
  { label: "Brazil", code: "BR", currency: "BRL" },
  { label: "Brunei", code: "BN", currency: "BND" },
  { label: "Bulgaria", code: "BG", currency: "BGN" },
  { label: "Burkina Faso", code: "BF", currency: "XOF" },
  { label: "Burundi", code: "BI", currency: "BIF" },
  { label: "Cambodia", code: "KH", currency: "KHR" },
  { label: "Cameroon", code: "CM", currency: "XAF" },
  { label: "Canada", code: "CA", currency: "CAD" },
  { label: "Cape Verde", code: "CV", currency: "CVE" },
  { label: "Central African Republic", code: "CF", currency: "XAF" },
  { label: "Chad", code: "TD", currency: "XAF" },
  { label: "Chile", code: "CL", currency: "CLP" },
  { label: "China", code: "CN", currency: "CNY" },
  { label: "Colombia", code: "CO", currency: "COP" },
  { label: "Comoros", code: "KM", currency: "KMF" },
  { label: "Congo", code: "CG", currency: "XAF" },
  { label: "Costa Rica", code: "CR", currency: "CRC" },
  { label: "Croatia", code: "HR", currency: "EUR" },
  { label: "Cuba", code: "CU", currency: "CUP" },
  { label: "Cyprus", code: "CY", currency: "EUR" },
  { label: "Czech Republic", code: "CZ", currency: "CZK" },
  { label: "Denmark", code: "DK", currency: "DKK" },
  { label: "Djibouti", code: "DJ", currency: "DJF" },
  { label: "Dominican Republic", code: "DO", currency: "DOP" },
  { label: "Ecuador", code: "EC", currency: "USD" },
  { label: "Egypt", code: "EG", currency: "EGP" },
  { label: "El Salvador", code: "SV", currency: "USD" },
  { label: "Estonia", code: "EE", currency: "EUR" },
  { label: "Ethiopia", code: "ET", currency: "ETB" },
  { label: "Fiji", code: "FJ", currency: "FJD" },
  { label: "Finland", code: "FI", currency: "EUR" },
  { label: "France", code: "FR", currency: "EUR" },
  { label: "Gabon", code: "GA", currency: "XAF" },
  { label: "Gambia", code: "GM", currency: "GMD" },
  { label: "Georgia", code: "GE", currency: "GEL" },
  { label: "Germany", code: "DE", currency: "EUR" },
  { label: "Ghana", code: "GH", currency: "GHS" },
  { label: "Greece", code: "GR", currency: "EUR" },
  { label: "Guatemala", code: "GT", currency: "GTQ" },
  { label: "Guinea", code: "GN", currency: "GNF" },
  { label: "Guyana", code: "GY", currency: "GYD" },
  { label: "Haiti", code: "HT", currency: "HTG" },
  { label: "Honduras", code: "HN", currency: "HNL" },
  { label: "Hong Kong", code: "HK", currency: "HKD" },
  { label: "Hungary", code: "HU", currency: "HUF" },
  { label: "Iceland", code: "IS", currency: "ISK" },
  { label: "India", code: "IN", currency: "INR" },
  { label: "Indonesia", code: "ID", currency: "IDR" },
  { label: "Iran", code: "IR", currency: "IRR" },
  { label: "Iraq", code: "IQ", currency: "IQD" },
  { label: "Ireland", code: "IE", currency: "EUR" },
  { label: "Israel", code: "IL", currency: "ILS" },
  { label: "Italy", code: "IT", currency: "EUR" },
  { label: "Jamaica", code: "JM", currency: "JMD" },
  { label: "Japan", code: "JP", currency: "JPY" },
  { label: "Jordan", code: "JO", currency: "JOD" },
  { label: "Kazakhstan", code: "KZ", currency: "KZT" },
  { label: "Kenya", code: "KE", currency: "KES" },
  { label: "Kuwait", code: "KW", currency: "KWD" },
  { label: "Kyrgyzstan", code: "KG", currency: "KGS" },
  { label: "Laos", code: "LA", currency: "LAK" },
  { label: "Latvia", code: "LV", currency: "EUR" },
  { label: "Lebanon", code: "LB", currency: "LBP" },
  { label: "Libya", code: "LY", currency: "LYD" },
  { label: "Liechtenstein", code: "LI", currency: "CHF" },
  { label: "Lithuania", code: "LT", currency: "EUR" },
  { label: "Luxembourg", code: "LU", currency: "EUR" },
  { label: "Madagascar", code: "MG", currency: "MGA" },
  { label: "Malawi", code: "MW", currency: "MWK" },
  { label: "Malaysia", code: "MY", currency: "MYR" },
  { label: "Maldives", code: "MV", currency: "MVR" },
  { label: "Mali", code: "ML", currency: "XOF" },
  { label: "Malta", code: "MT", currency: "EUR" },
  { label: "Mauritania", code: "MR", currency: "MRU" },
  { label: "Mauritius", code: "MU", currency: "MUR" },
  { label: "Mexico", code: "MX", currency: "MXN" },
  { label: "Moldova", code: "MD", currency: "MDL" },
  { label: "Mongolia", code: "MN", currency: "MNT" },
  { label: "Montenegro", code: "ME", currency: "EUR" },
  { label: "Morocco", code: "MA", currency: "MAD" },
  { label: "Mozambique", code: "MZ", currency: "MZN" },
  { label: "Myanmar", code: "MM", currency: "MMK" },
  { label: "Namibia", code: "NA", currency: "NAD" },
  { label: "Nepal", code: "NP", currency: "NPR" },
  { label: "Netherlands", code: "NL", currency: "EUR" },
  { label: "New Zealand", code: "NZ", currency: "NZD" },
  { label: "Nicaragua", code: "NI", currency: "NIO" },
  { label: "Niger", code: "NE", currency: "XOF" },
  { label: "Nigeria", code: "NG", currency: "NGN" },
  { label: "North Korea", code: "KP", currency: "KPW" },
  { label: "North Macedonia", code: "MK", currency: "MKD" },
  { label: "Norway", code: "NO", currency: "NOK" },
  { label: "Oman", code: "OM", currency: "OMR" },
  { label: "Pakistan", code: "PK", currency: "PKR" },
  { label: "Panama", code: "PA", currency: "PAB" },
  { label: "Paraguay", code: "PY", currency: "PYG" },
  { label: "Peru", code: "PE", currency: "PEN" },
  { label: "Philippines", code: "PH", currency: "PHP" },
  { label: "Poland", code: "PL", currency: "PLN" },
  { label: "Portugal", code: "PT", currency: "EUR" },
  { label: "Qatar", code: "QA", currency: "QAR" },
  { label: "Romania", code: "RO", currency: "RON" },
  { label: "Russia", code: "RU", currency: "RUB" },
  { label: "Rwanda", code: "RW", currency: "RWF" },
  { label: "Saudi Arabia", code: "SA", currency: "SAR" },
  { label: "Senegal", code: "SN", currency: "XOF" },
  { label: "Serbia", code: "RS", currency: "RSD" },
  { label: "Sierra Leone", code: "SL", currency: "SLL" },
  { label: "Singapore", code: "SG", currency: "SGD" },
  { label: "Slovakia", code: "SK", currency: "EUR" },
  { label: "Slovenia", code: "SI", currency: "EUR" },
  { label: "Somalia", code: "SO", currency: "SOS" },
  { label: "South Africa", code: "ZA", currency: "ZAR" },
  { label: "South Korea", code: "KR", currency: "KRW" },
  { label: "Spain", code: "ES", currency: "EUR" },
  { label: "Sri Lanka", code: "LK", currency: "LKR" },
  { label: "Sudan", code: "SD", currency: "SDG" },
  { label: "Suriname", code: "SR", currency: "SRD" },
  { label: "Sweden", code: "SE", currency: "SEK" },
  { label: "Switzerland", code: "CH", currency: "CHF" },
  { label: "Syria", code: "SY", currency: "SYP" },
  { label: "Taiwan", code: "TW", currency: "TWD" },
  { label: "Tajikistan", code: "TJ", currency: "TJS" },
  { label: "Tanzania", code: "TZ", currency: "TZS" },
  { label: "Thailand", code: "TH", currency: "THB" },
  { label: "Togo", code: "TG", currency: "XOF" },
  { label: "Tunisia", code: "TN", currency: "TND" },
  { label: "Turkey", code: "TR", currency: "TRY" },
  { label: "Turkmenistan", code: "TM", currency: "TMT" },
  { label: "Uganda", code: "UG", currency: "UGX" },
  { label: "Ukraine", code: "UA", currency: "UAH" },
  { label: "United Arab Emirates", code: "AE", currency: "AED" },
  { label: "United Kingdom", code: "GB", currency: "GBP" },
  { label: "United States", code: "US", currency: "USD" },
  { label: "Uruguay", code: "UY", currency: "UYU" },
  { label: "Uzbekistan", code: "UZ", currency: "UZS" },
  { label: "Vatican City", code: "VA", currency: "EUR" },
  { label: "Venezuela", code: "VE", currency: "VES" },
  { label: "Vietnam", code: "VN", currency: "VND" },
  { label: "Yemen", code: "YE", currency: "YER" },
  { label: "Zambia", code: "ZM", currency: "ZMW" },
  { label: "Zimbabwe", code: "ZW", currency: "ZWL" },
];

export const countryCurrencyMap = Object.fromEntries(
  allCountries.map(c => [c.label, c.currency])
);

export const countryCodeMap = Object.fromEntries(
  allCountries.map(c => [c.label, c.code])
);
